# Pytorch

### Understand PyTorch’s Tensor library functions

An short introduction about PyTorch and about the chosen functions. 
- function 1 - torch.device()
- function 2 - torch.zeros()
- function 3 - torch.numel()
- function 4 - view()
- function 5 - torch.arange()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.device

A torch.device is an object representing the device on which a torch.Tensor is or will be allocated.

In [2]:
# Example 1
torch.device('cuda:0')

device(type='cuda', index=0)

Type of device is CUDA [Enables GPU usage]

In [3]:
# Example 2 - 
torch.device('cpu')

device(type='cpu')

Type of device is cpu [Enables CPU usage]

In [4]:
# Example 3 -
torch.device('cuda’:0)

SyntaxError: EOL while scanning string literal (<ipython-input-4-a57b2fc60e7b>, line 2)

The torch.device argument in functions can generally be substituted with a string.

torch.device should be used when we want to select the program to run on CPU or GPU device.

## Function 2 - torch.zeros

creates an array of zero with required dimension passed as parameter

In [5]:
# Example 1 - working
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


created an 5*3 matrix with all zero values with data type long

In [6]:
# Example 2 - working
x = torch.zeros(5, dtype=torch.float64)
print(x)

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


created a 1*5 array with zero values in float datatype

In [7]:
# Example 3 - breaking
# syntax error, argument always accepts int values
x = torch.zeros(3,2.0,4)
print(x)

TypeError: zeros(): argument 'size' must be tuple of ints, but found element of type float at pos 2

torch.zeros creates an array of zero value.

An example when you want to display a black image you set the dimension of image with 2*2 matrix

## Function 3 - torch.numel()

Returns the total number of elements in the input tensor.

In [8]:
# Example 1 - working
a = torch.randn(9, 8)
torch.numel(a)

72

9*8 is the total number of elements

In [9]:
# Example 2 - working
a = torch.randn(9, 8, 7)
torch.numel(a)

504

9* 8* 7 is the total number of elements

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.zeros(3,2.0,4)
torch.numel(x)

TypeError: zeros(): argument 'size' must be tuple of ints, but found element of type float at pos 2

torch.numel() will accept only the int values, take care of datatype.

The above function can be used when we want to know the number of elements in the given array.

## Function 4 - view()

View avoids explicit data copy, and allows us to do fast and memory efficient **reshaping**, slicing and element-wise operations.

In [16]:
# Example 1 - working
t = torch.rand(5, 4)
b = t.view(2, 10)
b

tensor([[0.8653, 0.7008, 0.7192, 0.4913, 0.5719, 0.2443, 0.0201, 0.3436, 0.8407,
         0.7728],
        [0.9766, 0.6390, 0.5444, 0.0574, 0.5083, 0.1931, 0.8069, 0.7621, 0.6441,
         0.9118]])

In the above example we reshaped the array of (5,4) to (2,10)

In [17]:
# Example 2 - working
t = torch.rand(5, 5, 5)
b = t.view(5, 25)
b

tensor([[0.2786, 0.8061, 0.6767, 0.6917, 0.2716, 0.2887, 0.0223, 0.9432, 0.5377,
         0.9733, 0.0203, 0.9244, 0.8477, 0.2185, 0.8306, 0.0322, 0.2560, 0.7756,
         0.3911, 0.3239, 0.6194, 0.0266, 0.9533, 0.0471, 0.7267],
        [0.7629, 0.0738, 0.2315, 0.0117, 0.5972, 0.0821, 0.0482, 0.8814, 0.0936,
         0.9625, 0.3755, 0.0389, 0.7243, 0.2425, 0.7460, 0.0358, 0.7001, 0.8885,
         0.1942, 0.2569, 0.7277, 0.9297, 0.5702, 0.6940, 0.1024],
        [0.8453, 0.9967, 0.7199, 0.0356, 0.8646, 0.7775, 0.5611, 0.0848, 0.9463,
         0.3022, 0.0804, 0.9477, 0.6436, 0.4274, 0.3777, 0.0760, 0.6201, 0.6662,
         0.2306, 0.2577, 0.8652, 0.3195, 0.9583, 0.0013, 0.9361],
        [0.1503, 0.3945, 0.1811, 0.3156, 0.7096, 0.7272, 0.1722, 0.0046, 0.8206,
         0.0674, 0.5951, 0.5941, 0.7322, 0.3527, 0.9877, 0.1357, 0.9939, 0.2718,
         0.2502, 0.4494, 0.9825, 0.0589, 0.0331, 0.6988, 0.7346],
        [0.3497, 0.1907, 0.6127, 0.1352, 0.2705, 0.4350, 0.0194, 0.1557, 0.2409,
       

In the above example we reshaped the array of (5,5,5) to (5,25)

In [18]:
# Example 3 - breaking
t = torch.rand(5, 5, 5)
b = t.view(5, 20)
b

RuntimeError: shape '[5, 20]' is invalid for input of size 125

Whenever we do reshape we need to ensure to handle the number of elements.
If there is any situation that you don't know how many rows you want but are sure of the number of columns, then you can specify this with a -1 i.e. t.view(-1)

Closing comments about when to use this function

## Function 5 - torch.arange()

Returns a tensor of size [start, end) taken with common difference step beginning from start.

In [23]:
# Example 1 - working
torch.arange(18).view(3,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

A range 18 numbers is generated with the step size of 1

In [29]:
# Example 2 - working
torch.arange(2,4, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000])

A range of numbers is generated with the step size of 0.5 between 2 and 4

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(18, 1.5, 1)

RuntimeError: upper bound and larger bound inconsistent with step sign

Upper bound and lower bounding values need to tackled

torch.arange can be used when we need to generate a fixed dimension of numbers with step size

## Conclusion

In this notebook I have explained all basic and important torch functions which we use in day to day coding with pytorch. Now we can start using this in our upcoming lecture for developing good programs.

## Reference Links
Interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://www.youtube.com/watch?v=4MpZIoV_g7k

In [33]:
!pip install jovian --upgrade --quiet

In [34]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
